# Generated by Django 6.0.2 on 2026-02-27 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userseasonstats',
            options={'ordering': ['-playoff_points', '-total_confidence_points']},
        ),
        migrations.AddField(
            model_name='userseasonstats',
            name='playoff_points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WeeklyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_points', models.IntegerField(default=0)),
                ('weekly_rank', models.IntegerField(blank=True, null=True)),
                ('playoff_points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_results', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_results', to='pool.week')),
            ],
            options={
                'ordering': ['week', '-confidence_points'],
                'unique_together': {('user', 'week')},
            },
        ),
    ]
